/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Team = IDL.Variant({
  'patliputraLeaders' : IDL.Null,
  'tirhutChallengers' : IDL.Null,
  'mithilaPride' : IDL.Null,
  'bhojpurFighters' : IDL.Null,
  'seemanchalRiser' : IDL.Null,
  'magadhUnited' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreatePaymentResponse = IDL.Record({
  'checkoutUrl' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileUpload = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const AdminDashboardStats = IDL.Record({
  'pendingPayments' : IDL.Nat,
  'totalTeams' : IDL.Nat,
  'anonymousRegistrations' : IDL.Nat,
  'totalSponsorInquiries' : IDL.Nat,
  'authenticatedRegistrations' : IDL.Nat,
  'pendingSponsorInquiries' : IDL.Nat,
  'paidRegistrations' : IDL.Nat,
  'totalRegistrations' : IDL.Nat,
});
export const JerseySize = IDL.Variant({
  'l40' : IDL.Null,
  'm38' : IDL.Null,
  's36' : IDL.Null,
  'xl42' : IDL.Null,
  'xxxl46' : IDL.Null,
  'xxl44' : IDL.Null,
});
export const CricketExperience = IDL.Variant({
  'academy' : IDL.Null,
  'district' : IDL.Null,
  'state' : IDL.Null,
});
export const PlayerCategory = IDL.Variant({
  'allRounder' : IDL.Null,
  'bowler' : IDL.Null,
  'wicketkeeper' : IDL.Null,
  'batsman' : IDL.Null,
});
export const PlayerRegistration = IDL.Record({
  'age' : IDL.Nat,
  'paymentStatus' : IDL.Bool,
  'contact' : IDL.Text,
  'jerseySize' : JerseySize,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'experience' : CricketExperience,
  'timestamp' : IDL.Nat,
  'category' : PlayerCategory,
  'teamChoice' : Team,
  'aadhaarNumber' : IDL.Text,
});
export const ContentPage = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'lastUpdated' : IDL.Nat,
});
export const SponsorInquiryStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'contacted' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const SponsorInquiry = IDL.Record({
  'status' : SponsorInquiryStatus,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat,
  'sponsorshipLevel' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const RegistrationAnalytics = IDL.Record({
  'byTeam' : IDL.Vec(IDL.Tuple(Team, IDL.Nat)),
  'byJerseySize' : IDL.Vec(IDL.Tuple(JerseySize, IDL.Nat)),
  'byExperience' : IDL.Vec(IDL.Tuple(CricketExperience, IDL.Nat)),
  'byCategory' : IDL.Vec(IDL.Tuple(PlayerCategory, IDL.Nat)),
});
export const TeamInfo = IDL.Record({
  'teamType' : Team,
  'owner' : IDL.Opt(IDL.Text),
  'logo' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'purse' : IDL.Nat,
});
export const PaymentCancelResponse = IDL.Record({
  'message' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const PaymentSuccessResponse = IDL.Record({
  'message' : IDL.Text,
  'payment' : IDL.Record({
    'status' : IDL.Text,
    'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  }),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTeamInfo' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat, Team],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkout' : IDL.Func([], [CreatePaymentResponse], []),
  'deleteContentPage' : IDL.Func([IDL.Text], [], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'deleteSponsorInquiry' : IDL.Func([IDL.Nat], [], []),
  'filterFilesByPrefix' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FileUpload)],
      ['query'],
    ),
  'getAdminDashboardStats' : IDL.Func([], [AdminDashboardStats], ['query']),
  'getAllAnonymousRegistrations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PlayerRegistration))],
      ['query'],
    ),
  'getAllContentPages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ContentPage))],
      ['query'],
    ),
  'getAllFiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, FileUpload))],
      ['query'],
    ),
  'getAllPlayerRegistrations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerRegistration))],
      ['query'],
    ),
  'getAllSponsorInquiries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, SponsorInquiry))],
      ['query'],
    ),
  'getCallerIdAsText' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContent' : IDL.Func([IDL.Text], [ContentPage], ['query']),
  'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileUpload)], ['query']),
  'getPlayerRegistration' : IDL.Func(
      [],
      [IDL.Opt(PlayerRegistration)],
      ['query'],
    ),
  'getPlayerRegistrationByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerRegistration)],
      ['query'],
    ),
  'getRegistrationAnalytics' : IDL.Func([], [RegistrationAnalytics], ['query']),
  'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSortedTeamInfos' : IDL.Func([], [IDL.Vec(TeamInfo)], ['query']),
  'getTeams' : IDL.Func([], [IDL.Vec(TeamInfo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(PlayerCategory)], ['query']),
  'listExperienceLevels' : IDL.Func(
      [],
      [IDL.Vec(CricketExperience)],
      ['query'],
    ),
  'listJerseySizes' : IDL.Func([], [IDL.Vec(JerseySize)], ['query']),
  'listTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
  'paymentSuccess' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [PaymentSuccessResponse],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setupStripePrices' : IDL.Func([], [], []),
  'submitPlayerRegistration' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        CricketExperience,
        Team,
        PlayerCategory,
        JerseySize,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'submitSponsorInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePlayerPaymentStatus' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Text), IDL.Bool],
      [],
      [],
    ),
  'updateSponsorInquiryStatus' : IDL.Func(
      [IDL.Nat, SponsorInquiryStatus],
      [],
      [],
    ),
  'updateTeamInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat, Team],
      [],
      [],
    ),
  'updateTeamLogo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTeamPurse' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Team = IDL.Variant({
    'patliputraLeaders' : IDL.Null,
    'tirhutChallengers' : IDL.Null,
    'mithilaPride' : IDL.Null,
    'bhojpurFighters' : IDL.Null,
    'seemanchalRiser' : IDL.Null,
    'magadhUnited' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreatePaymentResponse = IDL.Record({
    'checkoutUrl' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileUpload = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const AdminDashboardStats = IDL.Record({
    'pendingPayments' : IDL.Nat,
    'totalTeams' : IDL.Nat,
    'anonymousRegistrations' : IDL.Nat,
    'totalSponsorInquiries' : IDL.Nat,
    'authenticatedRegistrations' : IDL.Nat,
    'pendingSponsorInquiries' : IDL.Nat,
    'paidRegistrations' : IDL.Nat,
    'totalRegistrations' : IDL.Nat,
  });
  const JerseySize = IDL.Variant({
    'l40' : IDL.Null,
    'm38' : IDL.Null,
    's36' : IDL.Null,
    'xl42' : IDL.Null,
    'xxxl46' : IDL.Null,
    'xxl44' : IDL.Null,
  });
  const CricketExperience = IDL.Variant({
    'academy' : IDL.Null,
    'district' : IDL.Null,
    'state' : IDL.Null,
  });
  const PlayerCategory = IDL.Variant({
    'allRounder' : IDL.Null,
    'bowler' : IDL.Null,
    'wicketkeeper' : IDL.Null,
    'batsman' : IDL.Null,
  });
  const PlayerRegistration = IDL.Record({
    'age' : IDL.Nat,
    'paymentStatus' : IDL.Bool,
    'contact' : IDL.Text,
    'jerseySize' : JerseySize,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'experience' : CricketExperience,
    'timestamp' : IDL.Nat,
    'category' : PlayerCategory,
    'teamChoice' : Team,
    'aadhaarNumber' : IDL.Text,
  });
  const ContentPage = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'lastUpdated' : IDL.Nat,
  });
  const SponsorInquiryStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'contacted' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const SponsorInquiry = IDL.Record({
    'status' : SponsorInquiryStatus,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
    'sponsorshipLevel' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const RegistrationAnalytics = IDL.Record({
    'byTeam' : IDL.Vec(IDL.Tuple(Team, IDL.Nat)),
    'byJerseySize' : IDL.Vec(IDL.Tuple(JerseySize, IDL.Nat)),
    'byExperience' : IDL.Vec(IDL.Tuple(CricketExperience, IDL.Nat)),
    'byCategory' : IDL.Vec(IDL.Tuple(PlayerCategory, IDL.Nat)),
  });
  const TeamInfo = IDL.Record({
    'teamType' : Team,
    'owner' : IDL.Opt(IDL.Text),
    'logo' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'purse' : IDL.Nat,
  });
  const PaymentCancelResponse = IDL.Record({
    'message' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const PaymentSuccessResponse = IDL.Record({
    'message' : IDL.Text,
    'payment' : IDL.Record({
      'status' : IDL.Text,
      'paymentMethod' : IDL.Record({ 'last4' : IDL.Text, 'brand' : IDL.Text }),
      'currency' : IDL.Text,
      'amount' : IDL.Nat,
    }),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTeamInfo' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat, Team],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkout' : IDL.Func([], [CreatePaymentResponse], []),
    'deleteContentPage' : IDL.Func([IDL.Text], [], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'deleteSponsorInquiry' : IDL.Func([IDL.Nat], [], []),
    'filterFilesByPrefix' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FileUpload)],
        ['query'],
      ),
    'getAdminDashboardStats' : IDL.Func([], [AdminDashboardStats], ['query']),
    'getAllAnonymousRegistrations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PlayerRegistration))],
        ['query'],
      ),
    'getAllContentPages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ContentPage))],
        ['query'],
      ),
    'getAllFiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, FileUpload))],
        ['query'],
      ),
    'getAllPlayerRegistrations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerRegistration))],
        ['query'],
      ),
    'getAllSponsorInquiries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, SponsorInquiry))],
        ['query'],
      ),
    'getCallerIdAsText' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContent' : IDL.Func([IDL.Text], [ContentPage], ['query']),
    'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileUpload)], ['query']),
    'getPlayerRegistration' : IDL.Func(
        [],
        [IDL.Opt(PlayerRegistration)],
        ['query'],
      ),
    'getPlayerRegistrationByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerRegistration)],
        ['query'],
      ),
    'getRegistrationAnalytics' : IDL.Func(
        [],
        [RegistrationAnalytics],
        ['query'],
      ),
    'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSortedTeamInfos' : IDL.Func([], [IDL.Vec(TeamInfo)], ['query']),
    'getTeams' : IDL.Func([], [IDL.Vec(TeamInfo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(PlayerCategory)], ['query']),
    'listExperienceLevels' : IDL.Func(
        [],
        [IDL.Vec(CricketExperience)],
        ['query'],
      ),
    'listJerseySizes' : IDL.Func([], [IDL.Vec(JerseySize)], ['query']),
    'listTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'paymentCancel' : IDL.Func([IDL.Text], [PaymentCancelResponse], []),
    'paymentSuccess' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PaymentSuccessResponse],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setupStripePrices' : IDL.Func([], [], []),
    'submitPlayerRegistration' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          CricketExperience,
          Team,
          PlayerCategory,
          JerseySize,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'submitSponsorInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePlayerPaymentStatus' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Text), IDL.Bool],
        [],
        [],
      ),
    'updateSponsorInquiryStatus' : IDL.Func(
        [IDL.Nat, SponsorInquiryStatus],
        [],
        [],
      ),
    'updateTeamInfo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Nat,
          Team,
        ],
        [],
        [],
      ),
    'updateTeamLogo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTeamPurse' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };