/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminDashboardStats {
  'pendingPayments' : bigint,
  'totalTeams' : bigint,
  'anonymousRegistrations' : bigint,
  'totalSponsorInquiries' : bigint,
  'authenticatedRegistrations' : bigint,
  'pendingSponsorInquiries' : bigint,
  'paidRegistrations' : bigint,
  'totalRegistrations' : bigint,
}
export interface ContentPage {
  'title' : string,
  'content' : string,
  'lastUpdated' : bigint,
}
export interface CreatePaymentResponse {
  'checkoutUrl' : string,
  'sessionId' : string,
}
export type CricketExperience = { 'academy' : null } |
  { 'district' : null } |
  { 'state' : null };
export type ExternalBlob = Uint8Array;
export interface FileUpload {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'timestamp' : bigint,
}
export type JerseySize = { 'l40' : null } |
  { 'm38' : null } |
  { 's36' : null } |
  { 'xl42' : null } |
  { 'xxxl46' : null } |
  { 'xxl44' : null };
export interface PaymentCancelResponse {
  'message' : string,
  'sessionId' : string,
}
export interface PaymentSuccessResponse {
  'message' : string,
  'payment' : {
    'status' : string,
    'paymentMethod' : { 'last4' : string, 'brand' : string },
    'currency' : string,
    'amount' : bigint,
  },
}
export type PlayerCategory = { 'allRounder' : null } |
  { 'bowler' : null } |
  { 'wicketkeeper' : null } |
  { 'batsman' : null };
export interface PlayerRegistration {
  'age' : bigint,
  'paymentStatus' : boolean,
  'contact' : string,
  'jerseySize' : JerseySize,
  'name' : string,
  'email' : string,
  'experience' : CricketExperience,
  'timestamp' : bigint,
  'category' : PlayerCategory,
  'teamChoice' : Team,
  'aadhaarNumber' : string,
}
export interface RegistrationAnalytics {
  'byTeam' : Array<[Team, bigint]>,
  'byJerseySize' : Array<[JerseySize, bigint]>,
  'byExperience' : Array<[CricketExperience, bigint]>,
  'byCategory' : Array<[PlayerCategory, bigint]>,
}
export interface SponsorInquiry {
  'status' : SponsorInquiryStatus,
  'contact' : string,
  'name' : string,
  'company' : string,
  'message' : string,
  'timestamp' : bigint,
  'sponsorshipLevel' : string,
}
export type SponsorInquiryStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'contacted' : null } |
  { 'confirmed' : null };
export type Team = { 'patliputraLeaders' : null } |
  { 'tirhutChallengers' : null } |
  { 'mithilaPride' : null } |
  { 'bhojpurFighters' : null } |
  { 'seemanchalRiser' : null } |
  { 'magadhUnited' : null };
export interface TeamInfo {
  'teamType' : Team,
  'owner' : [] | [string],
  'logo' : [] | [string],
  'name' : string,
  'purse' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTeamInfo' : ActorMethod<
    [string, [] | [string], [] | [string], bigint, Team],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'becomeFirstAdmin' : ActorMethod<[], undefined>,
  'checkout' : ActorMethod<[], CreatePaymentResponse>,
  'deleteContentPage' : ActorMethod<[string], undefined>,
  'deleteFile' : ActorMethod<[string], undefined>,
  'deleteSponsorInquiry' : ActorMethod<[bigint], undefined>,
  'filterFilesByPrefix' : ActorMethod<[string], Array<FileUpload>>,
  'getAdminDashboardStats' : ActorMethod<[], AdminDashboardStats>,
  'getAllAnonymousRegistrations' : ActorMethod<
    [],
    Array<[string, PlayerRegistration]>
  >,
  'getAllContentPages' : ActorMethod<[], Array<[string, ContentPage]>>,
  'getAllFiles' : ActorMethod<[], Array<[string, FileUpload]>>,
  'getAllPlayerRegistrations' : ActorMethod<
    [],
    Array<[Principal, PlayerRegistration]>
  >,
  'getAllSponsorInquiries' : ActorMethod<[], Array<[bigint, SponsorInquiry]>>,
  'getCallerIdAsText' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContent' : ActorMethod<[string], ContentPage>,
  'getFile' : ActorMethod<[string], [] | [FileUpload]>,
  'getPlayerRegistration' : ActorMethod<[], [] | [PlayerRegistration]>,
  'getPlayerRegistrationByPrincipal' : ActorMethod<
    [Principal],
    [] | [PlayerRegistration]
  >,
  'getRegistrationAnalytics' : ActorMethod<[], RegistrationAnalytics>,
  'getRegistrationCount' : ActorMethod<[], bigint>,
  'getSortedTeamInfos' : ActorMethod<[], Array<TeamInfo>>,
  'getTeams' : ActorMethod<[], Array<TeamInfo>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSystemBootstrapNeeded' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<PlayerCategory>>,
  'listExperienceLevels' : ActorMethod<[], Array<CricketExperience>>,
  'listJerseySizes' : ActorMethod<[], Array<JerseySize>>,
  'listTeams' : ActorMethod<[], Array<Team>>,
  'paymentCancel' : ActorMethod<[string], PaymentCancelResponse>,
  'paymentSuccess' : ActorMethod<
    [string, string, string],
    PaymentSuccessResponse
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setupStripePrices' : ActorMethod<[], undefined>,
  'submitPlayerRegistration' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      string,
      CricketExperience,
      Team,
      PlayerCategory,
      JerseySize,
      boolean,
      [] | [string],
      boolean,
    ],
    undefined
  >,
  'submitSponsorInquiry' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'updateContent' : ActorMethod<[string, string, string], undefined>,
  'updatePlayerPaymentStatus' : ActorMethod<
    [[] | [Principal], [] | [string], boolean],
    undefined
  >,
  'updateSponsorInquiryStatus' : ActorMethod<
    [bigint, SponsorInquiryStatus],
    undefined
  >,
  'updateTeamInfo' : ActorMethod<
    [string, string, [] | [string], [] | [string], bigint, Team],
    undefined
  >,
  'updateTeamLogo' : ActorMethod<[string, string], undefined>,
  'updateTeamPurse' : ActorMethod<[string, bigint], undefined>,
  'uploadFile' : ActorMethod<[string, ExternalBlob], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];