/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreatePaymentResponse {
    checkoutUrl: string;
    sessionId: string;
}
export interface TeamInfo {
    teamType: Team;
    owner?: string;
    logo?: string;
    name: string;
    purse: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface AdminDashboardStats {
    pendingPayments: bigint;
    totalTeams: bigint;
    anonymousRegistrations: bigint;
    totalSponsorInquiries: bigint;
    authenticatedRegistrations: bigint;
    pendingSponsorInquiries: bigint;
    paidRegistrations: bigint;
    totalRegistrations: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PaymentSuccessResponse {
    message: string;
    payment: {
        status: string;
        paymentMethod: {
            last4: string;
            brand: string;
        };
        currency: string;
        amount: bigint;
    };
}
export interface FileUpload {
    id: string;
    blob: ExternalBlob;
    name: string;
    timestamp: bigint;
}
export interface SponsorInquiry {
    status: SponsorInquiryStatus;
    contact: string;
    name: string;
    company: string;
    message: string;
    timestamp: bigint;
    sponsorshipLevel: string;
}
export interface RegistrationAnalytics {
    byTeam: Array<[Team, bigint]>;
    byJerseySize: Array<[JerseySize, bigint]>;
    byExperience: Array<[CricketExperience, bigint]>;
    byCategory: Array<[PlayerCategory, bigint]>;
}
export interface PlayerRegistration {
    age: bigint;
    paymentStatus: boolean;
    contact: string;
    jerseySize: JerseySize;
    name: string;
    email: string;
    experience: CricketExperience;
    timestamp: bigint;
    category: PlayerCategory;
    teamChoice: Team;
    aadhaarNumber: string;
}
export interface PaymentCancelResponse {
    message: string;
    sessionId: string;
}
export interface ContentPage {
    title: string;
    content: string;
    lastUpdated: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
    phone?: string;
}
export enum CricketExperience {
    academy = "academy",
    district = "district",
    state = "state"
}
export enum JerseySize {
    l40 = "l40",
    m38 = "m38",
    s36 = "s36",
    xl42 = "xl42",
    xxxl46 = "xxxl46",
    xxl44 = "xxl44"
}
export enum PlayerCategory {
    allRounder = "allRounder",
    bowler = "bowler",
    wicketkeeper = "wicketkeeper",
    batsman = "batsman"
}
export enum SponsorInquiryStatus {
    pending = "pending",
    rejected = "rejected",
    contacted = "contacted",
    confirmed = "confirmed"
}
export enum Team {
    patliputraLeaders = "patliputraLeaders",
    tirhutChallengers = "tirhutChallengers",
    mithilaPride = "mithilaPride",
    bhojpurFighters = "bhojpurFighters",
    seemanchalRiser = "seemanchalRiser",
    magadhUnited = "magadhUnited"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTeamInfo(name: string, owner: string | null, logo: string | null, purse: bigint, teamType: Team): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkout(): Promise<CreatePaymentResponse>;
    deleteContentPage(pageId: string): Promise<void>;
    deleteFile(fileId: string): Promise<void>;
    deleteSponsorInquiry(inquiryId: bigint): Promise<void>;
    filterFilesByPrefix(prefix: string): Promise<Array<FileUpload>>;
    getAdminDashboardStats(): Promise<AdminDashboardStats>;
    getAllAnonymousRegistrations(): Promise<Array<[string, PlayerRegistration]>>;
    getAllContentPages(): Promise<Array<[string, ContentPage]>>;
    getAllFiles(): Promise<Array<[string, FileUpload]>>;
    getAllPlayerRegistrations(): Promise<Array<[Principal, PlayerRegistration]>>;
    getAllSponsorInquiries(): Promise<Array<[bigint, SponsorInquiry]>>;
    getCallerIdAsText(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContent(pageId: string): Promise<ContentPage>;
    getFile(fileId: string): Promise<FileUpload | null>;
    getPlayerRegistration(): Promise<PlayerRegistration | null>;
    getPlayerRegistrationByPrincipal(user: Principal): Promise<PlayerRegistration | null>;
    getRegistrationAnalytics(): Promise<RegistrationAnalytics>;
    getRegistrationCount(): Promise<bigint>;
    getSortedTeamInfos(): Promise<Array<TeamInfo>>;
    getTeams(): Promise<Array<TeamInfo>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listCategories(): Promise<Array<PlayerCategory>>;
    listExperienceLevels(): Promise<Array<CricketExperience>>;
    listJerseySizes(): Promise<Array<JerseySize>>;
    listTeams(): Promise<Array<Team>>;
    paymentCancel(sessionId: string): Promise<PaymentCancelResponse>;
    paymentSuccess(sessionId: string, accountId: string, caffeineCustomerId: string): Promise<PaymentSuccessResponse>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setupStripePrices(): Promise<void>;
    submitPlayerRegistration(name: string, age: bigint, contact: string, email: string, aadhaarNumber: string, experience: CricketExperience, teamChoice: Team, category: PlayerCategory, jerseySize: JerseySize, paymentStatus: boolean, userId: string | null, anonymous: boolean): Promise<void>;
    submitSponsorInquiry(name: string, company: string, contact: string, sponsorshipLevel: string, message: string): Promise<bigint>;
    updateContent(pageId: string, title: string, content: string): Promise<void>;
    updatePlayerPaymentStatus(userPrincipal: Principal | null, anonymousId: string | null, paymentStatus: boolean): Promise<void>;
    updateSponsorInquiryStatus(inquiryId: bigint, status: SponsorInquiryStatus): Promise<void>;
    updateTeamInfo(oldName: string, name: string, owner: string | null, logo: string | null, purse: bigint, teamType: Team): Promise<void>;
    updateTeamLogo(teamName: string, logo: string): Promise<void>;
    updateTeamPurse(teamName: string, purse: bigint): Promise<void>;
    uploadFile(name: string, blob: ExternalBlob): Promise<string>;
}
import type { CricketExperience as _CricketExperience, ExternalBlob as _ExternalBlob, FileUpload as _FileUpload, JerseySize as _JerseySize, PlayerCategory as _PlayerCategory, PlayerRegistration as _PlayerRegistration, RegistrationAnalytics as _RegistrationAnalytics, SponsorInquiry as _SponsorInquiry, SponsorInquiryStatus as _SponsorInquiryStatus, Team as _Team, TeamInfo as _TeamInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTeamInfo(arg0: string, arg1: string | null, arg2: string | null, arg3: bigint, arg4: Team): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeamInfo(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_Team_n9(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeamInfo(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_Team_n9(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkout(): Promise<CreatePaymentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.checkout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkout();
            return result;
        }
    }
    async deleteContentPage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContentPage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContentPage(arg0);
            return result;
        }
    }
    async deleteFile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteSponsorInquiry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSponsorInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSponsorInquiry(arg0);
            return result;
        }
    }
    async filterFilesByPrefix(arg0: string): Promise<Array<FileUpload>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterFilesByPrefix(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterFilesByPrefix(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminDashboardStats(): Promise<AdminDashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboardStats();
            return result;
        }
    }
    async getAllAnonymousRegistrations(): Promise<Array<[string, PlayerRegistration]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnonymousRegistrations();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnonymousRegistrations();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContentPages(): Promise<Array<[string, ContentPage]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContentPages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContentPages();
            return result;
        }
    }
    async getAllFiles(): Promise<Array<[string, FileUpload]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFiles();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFiles();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayerRegistrations(): Promise<Array<[Principal, PlayerRegistration]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayerRegistrations();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayerRegistrations();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSponsorInquiries(): Promise<Array<[bigint, SponsorInquiry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSponsorInquiries();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSponsorInquiries();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerIdAsText(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerIdAsText();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerIdAsText();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContent(arg0: string): Promise<ContentPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContent(arg0);
            return result;
        }
    }
    async getFile(arg0: string): Promise<FileUpload | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerRegistration(): Promise<PlayerRegistration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerRegistration();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerRegistration();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerRegistrationByPrincipal(arg0: Principal): Promise<PlayerRegistration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerRegistrationByPrincipal(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerRegistrationByPrincipal(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegistrationAnalytics(): Promise<RegistrationAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrationAnalytics();
                return from_candid_RegistrationAnalytics_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrationAnalytics();
            return from_candid_RegistrationAnalytics_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegistrationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrationCount();
            return result;
        }
    }
    async getSortedTeamInfos(): Promise<Array<TeamInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedTeamInfos();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedTeamInfos();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeams(): Promise<Array<TeamInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeams();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeams();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCategories(): Promise<Array<PlayerCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listExperienceLevels(): Promise<Array<CricketExperience>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExperienceLevels();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExperienceLevels();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listJerseySizes(): Promise<Array<JerseySize>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJerseySizes();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJerseySizes();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeams();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeams();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async paymentCancel(arg0: string): Promise<PaymentCancelResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.paymentCancel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.paymentCancel(arg0);
            return result;
        }
    }
    async paymentSuccess(arg0: string, arg1: string, arg2: string): Promise<PaymentSuccessResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.paymentSuccess(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.paymentSuccess(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setupStripePrices(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setupStripePrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setupStripePrices();
            return result;
        }
    }
    async submitPlayerRegistration(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: CricketExperience, arg6: Team, arg7: PlayerCategory, arg8: JerseySize, arg9: boolean, arg10: string | null, arg11: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPlayerRegistration(arg0, arg1, arg2, arg3, arg4, to_candid_CricketExperience_n66(this._uploadFile, this._downloadFile, arg5), to_candid_Team_n9(this._uploadFile, this._downloadFile, arg6), to_candid_PlayerCategory_n68(this._uploadFile, this._downloadFile, arg7), to_candid_JerseySize_n70(this._uploadFile, this._downloadFile, arg8), arg9, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg10), arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPlayerRegistration(arg0, arg1, arg2, arg3, arg4, to_candid_CricketExperience_n66(this._uploadFile, this._downloadFile, arg5), to_candid_Team_n9(this._uploadFile, this._downloadFile, arg6), to_candid_PlayerCategory_n68(this._uploadFile, this._downloadFile, arg7), to_candid_JerseySize_n70(this._uploadFile, this._downloadFile, arg8), arg9, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg10), arg11);
            return result;
        }
    }
    async submitSponsorInquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSponsorInquiry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSponsorInquiry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateContent(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContent(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePlayerPaymentStatus(arg0: Principal | null, arg1: string | null, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerPaymentStatus(to_candid_opt_n72(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerPaymentStatus(to_candid_opt_n72(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateSponsorInquiryStatus(arg0: bigint, arg1: SponsorInquiryStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSponsorInquiryStatus(arg0, to_candid_SponsorInquiryStatus_n73(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSponsorInquiryStatus(arg0, to_candid_SponsorInquiryStatus_n73(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTeamInfo(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: bigint, arg5: Team): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamInfo(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_Team_n9(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamInfo(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_Team_n9(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateTeamLogo(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamLogo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamLogo(arg0, arg1);
            return result;
        }
    }
    async updateTeamPurse(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamPurse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamPurse(arg0, arg1);
            return result;
        }
    }
    async uploadFile(arg0: string, arg1: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(arg0, await to_candid_ExternalBlob_n75(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(arg0, await to_candid_ExternalBlob_n75(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CricketExperience_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CricketExperience): CricketExperience {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FileUpload_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileUpload): Promise<FileUpload> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_JerseySize_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JerseySize): JerseySize {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerCategory): PlayerCategory {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerRegistration_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerRegistration): PlayerRegistration {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationAnalytics_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationAnalytics): RegistrationAnalytics {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_SponsorInquiryStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SponsorInquiryStatus): SponsorInquiryStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_SponsorInquiry_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SponsorInquiry): SponsorInquiry {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_TeamInfo_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamInfo): TeamInfo {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileUpload]): Promise<FileUpload | null> {
    return value.length === 0 ? null : await from_candid_FileUpload_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerRegistration]): PlayerRegistration | null {
    return value.length === 0 ? null : from_candid_PlayerRegistration_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
    name: string;
    timestamp: bigint;
}): Promise<{
    id: string;
    blob: ExternalBlob;
    name: string;
    timestamp: bigint;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        timestamp: value.timestamp
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    paymentStatus: boolean;
    contact: string;
    jerseySize: _JerseySize;
    name: string;
    email: string;
    experience: _CricketExperience;
    timestamp: bigint;
    category: _PlayerCategory;
    teamChoice: _Team;
    aadhaarNumber: string;
}): {
    age: bigint;
    paymentStatus: boolean;
    contact: string;
    jerseySize: JerseySize;
    name: string;
    email: string;
    experience: CricketExperience;
    timestamp: bigint;
    category: PlayerCategory;
    teamChoice: Team;
    aadhaarNumber: string;
} {
    return {
        age: value.age,
        paymentStatus: value.paymentStatus,
        contact: value.contact,
        jerseySize: from_candid_JerseySize_n21(_uploadFile, _downloadFile, value.jerseySize),
        name: value.name,
        email: value.email,
        experience: from_candid_CricketExperience_n23(_uploadFile, _downloadFile, value.experience),
        timestamp: value.timestamp,
        category: from_candid_PlayerCategory_n25(_uploadFile, _downloadFile, value.category),
        teamChoice: from_candid_Team_n27(_uploadFile, _downloadFile, value.teamChoice),
        aadhaarNumber: value.aadhaarNumber
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SponsorInquiryStatus;
    contact: string;
    name: string;
    company: string;
    message: string;
    timestamp: bigint;
    sponsorshipLevel: string;
}): {
    status: SponsorInquiryStatus;
    contact: string;
    name: string;
    company: string;
    message: string;
    timestamp: bigint;
    sponsorshipLevel: string;
} {
    return {
        status: from_candid_SponsorInquiryStatus_n37(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        name: value.name,
        company: value.company,
        message: value.message,
        timestamp: value.timestamp,
        sponsorshipLevel: value.sponsorshipLevel
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    email?: string;
    phone?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.email)),
        phone: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    byTeam: Array<[_Team, bigint]>;
    byJerseySize: Array<[_JerseySize, bigint]>;
    byExperience: Array<[_CricketExperience, bigint]>;
    byCategory: Array<[_PlayerCategory, bigint]>;
}): {
    byTeam: Array<[Team, bigint]>;
    byJerseySize: Array<[JerseySize, bigint]>;
    byExperience: Array<[CricketExperience, bigint]>;
    byCategory: Array<[PlayerCategory, bigint]>;
} {
    return {
        byTeam: from_candid_vec_n49(_uploadFile, _downloadFile, value.byTeam),
        byJerseySize: from_candid_vec_n51(_uploadFile, _downloadFile, value.byJerseySize),
        byExperience: from_candid_vec_n53(_uploadFile, _downloadFile, value.byExperience),
        byCategory: from_candid_vec_n55(_uploadFile, _downloadFile, value.byCategory)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teamType: _Team;
    owner: [] | [string];
    logo: [] | [string];
    name: string;
    purse: bigint;
}): {
    teamType: Team;
    owner?: string;
    logo?: string;
    name: string;
    purse: bigint;
} {
    return {
        teamType: from_candid_Team_n27(_uploadFile, _downloadFile, value.teamType),
        owner: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.owner)),
        logo: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.logo)),
        name: value.name,
        purse: value.purse
    };
}
function from_candid_tuple_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _PlayerRegistration]): [string, PlayerRegistration] {
    return [
        value[0],
        from_candid_PlayerRegistration_n19(_uploadFile, _downloadFile, value[1])
    ];
}
async function from_candid_tuple_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _FileUpload]): Promise<[string, FileUpload]> {
    return [
        value[0],
        await from_candid_FileUpload_n14(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _PlayerRegistration]): [Principal, PlayerRegistration] {
    return [
        value[0],
        from_candid_PlayerRegistration_n19(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _SponsorInquiry]): [bigint, SponsorInquiry] {
    return [
        value[0],
        from_candid_SponsorInquiry_n35(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Team, bigint]): [Team, bigint] {
    return [
        from_candid_Team_n27(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_JerseySize, bigint]): [JerseySize, bigint] {
    return [
        from_candid_JerseySize_n21(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_CricketExperience, bigint]): [CricketExperience, bigint] {
    return [
        from_candid_CricketExperience_n23(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_tuple_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_PlayerCategory, bigint]): [PlayerCategory, bigint] {
    return [
        from_candid_PlayerCategory_n25(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    l40: null;
} | {
    m38: null;
} | {
    s36: null;
} | {
    xl42: null;
} | {
    xxxl46: null;
} | {
    xxl44: null;
}): JerseySize {
    return "l40" in value ? JerseySize.l40 : "m38" in value ? JerseySize.m38 : "s36" in value ? JerseySize.s36 : "xl42" in value ? JerseySize.xl42 : "xxxl46" in value ? JerseySize.xxxl46 : "xxl44" in value ? JerseySize.xxl44 : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    academy: null;
} | {
    district: null;
} | {
    state: null;
}): CricketExperience {
    return "academy" in value ? CricketExperience.academy : "district" in value ? CricketExperience.district : "state" in value ? CricketExperience.state : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    allRounder: null;
} | {
    bowler: null;
} | {
    wicketkeeper: null;
} | {
    batsman: null;
}): PlayerCategory {
    return "allRounder" in value ? PlayerCategory.allRounder : "bowler" in value ? PlayerCategory.bowler : "wicketkeeper" in value ? PlayerCategory.wicketkeeper : "batsman" in value ? PlayerCategory.batsman : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patliputraLeaders: null;
} | {
    tirhutChallengers: null;
} | {
    mithilaPride: null;
} | {
    bhojpurFighters: null;
} | {
    seemanchalRiser: null;
} | {
    magadhUnited: null;
}): Team {
    return "patliputraLeaders" in value ? Team.patliputraLeaders : "tirhutChallengers" in value ? Team.tirhutChallengers : "mithilaPride" in value ? Team.mithilaPride : "bhojpurFighters" in value ? Team.bhojpurFighters : "seemanchalRiser" in value ? Team.seemanchalRiser : "magadhUnited" in value ? Team.magadhUnited : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    contacted: null;
} | {
    confirmed: null;
}): SponsorInquiryStatus {
    return "pending" in value ? SponsorInquiryStatus.pending : "rejected" in value ? SponsorInquiryStatus.rejected : "contacted" in value ? SponsorInquiryStatus.contacted : "confirmed" in value ? SponsorInquiryStatus.confirmed : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileUpload>): Promise<Array<FileUpload>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FileUpload_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _PlayerRegistration]>): Array<[string, PlayerRegistration]> {
    return value.map((x)=>from_candid_tuple_n18(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _FileUpload]>): Promise<Array<[string, FileUpload]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n30(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _PlayerRegistration]>): Array<[Principal, PlayerRegistration]> {
    return value.map((x)=>from_candid_tuple_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _SponsorInquiry]>): Array<[bigint, SponsorInquiry]> {
    return value.map((x)=>from_candid_tuple_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Team, bigint]>): Array<[Team, bigint]> {
    return value.map((x)=>from_candid_tuple_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_JerseySize, bigint]>): Array<[JerseySize, bigint]> {
    return value.map((x)=>from_candid_tuple_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_CricketExperience, bigint]>): Array<[CricketExperience, bigint]> {
    return value.map((x)=>from_candid_tuple_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_PlayerCategory, bigint]>): Array<[PlayerCategory, bigint]> {
    return value.map((x)=>from_candid_tuple_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamInfo>): Array<TeamInfo> {
    return value.map((x)=>from_candid_TeamInfo_n58(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerCategory>): Array<PlayerCategory> {
    return value.map((x)=>from_candid_PlayerCategory_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CricketExperience>): Array<CricketExperience> {
    return value.map((x)=>from_candid_CricketExperience_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JerseySize>): Array<JerseySize> {
    return value.map((x)=>from_candid_JerseySize_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n27(_uploadFile, _downloadFile, x));
}
function to_candid_CricketExperience_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CricketExperience): _CricketExperience {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_JerseySize_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JerseySize): _JerseySize {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_PlayerCategory_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerCategory): _PlayerCategory {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_SponsorInquiryStatus_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SponsorInquiryStatus): _SponsorInquiryStatus {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function to_candid_Team_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Team): _Team {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    phone?: string;
}): {
    name: string;
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Team): {
    patliputraLeaders: null;
} | {
    tirhutChallengers: null;
} | {
    mithilaPride: null;
} | {
    bhojpurFighters: null;
} | {
    seemanchalRiser: null;
} | {
    magadhUnited: null;
} {
    return value == Team.patliputraLeaders ? {
        patliputraLeaders: null
    } : value == Team.tirhutChallengers ? {
        tirhutChallengers: null
    } : value == Team.mithilaPride ? {
        mithilaPride: null
    } : value == Team.bhojpurFighters ? {
        bhojpurFighters: null
    } : value == Team.seemanchalRiser ? {
        seemanchalRiser: null
    } : value == Team.magadhUnited ? {
        magadhUnited: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CricketExperience): {
    academy: null;
} | {
    district: null;
} | {
    state: null;
} {
    return value == CricketExperience.academy ? {
        academy: null
    } : value == CricketExperience.district ? {
        district: null
    } : value == CricketExperience.state ? {
        state: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerCategory): {
    allRounder: null;
} | {
    bowler: null;
} | {
    wicketkeeper: null;
} | {
    batsman: null;
} {
    return value == PlayerCategory.allRounder ? {
        allRounder: null
    } : value == PlayerCategory.bowler ? {
        bowler: null
    } : value == PlayerCategory.wicketkeeper ? {
        wicketkeeper: null
    } : value == PlayerCategory.batsman ? {
        batsman: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JerseySize): {
    l40: null;
} | {
    m38: null;
} | {
    s36: null;
} | {
    xl42: null;
} | {
    xxxl46: null;
} | {
    xxl44: null;
} {
    return value == JerseySize.l40 ? {
        l40: null
    } : value == JerseySize.m38 ? {
        m38: null
    } : value == JerseySize.s36 ? {
        s36: null
    } : value == JerseySize.xl42 ? {
        xl42: null
    } : value == JerseySize.xxxl46 ? {
        xxxl46: null
    } : value == JerseySize.xxl44 ? {
        xxl44: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SponsorInquiryStatus): {
    pending: null;
} | {
    rejected: null;
} | {
    contacted: null;
} | {
    confirmed: null;
} {
    return value == SponsorInquiryStatus.pending ? {
        pending: null
    } : value == SponsorInquiryStatus.rejected ? {
        rejected: null
    } : value == SponsorInquiryStatus.contacted ? {
        contacted: null
    } : value == SponsorInquiryStatus.confirmed ? {
        confirmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
